[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "binip"
version = "0.0.1"
authors = [
    { name="Loïc James McKeever", email="loicjamesmckeever@gmail.com"},
]
description = "A package for facilitating various IP and subnet operations."
readme = "READ.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
